# Basic
title: Martin's Den
subtitle:
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@cauu</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# Navigation buttons in the front page.
nav:
  - { title: 首页, description: 前往首页, url: '/' }
  - { title: 全部, description: 按时间轴浏览, url: '/timeline' }
  - { title: 分类, description: 按标签浏览, url: '/category' }
  - { title: 项目, description: 项目和想法, url: '/project' }
  - { title: 读书, description: 豆瓣阅读, url: '/reading' }
  - { title: 关于, description: 关于我, url: '/about' }
  # - {title: Another Button, description: A button, url: 'http://example.com'}

project: 
  - { title: PokemonMax, description: 口袋妖怪GO精灵完美度计算器, url:  'http://www.poke-mon.cn' }
  - { title: IUFind, description: 哎哟旅行(全网旅行结伴信息搜索工具), url:  'http://www.iufind.com' }
  - { title: Spartan Wars, description: 在Tap4fun参与的第一个（也是最后一个）手游, url: 'http://www.tap4fun.com/spartan-wars/' }
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    duoshuo: cauu 
    
# Social
social:
    github: cauu
    mail: cauu@163.com
    douban: 
        name: cauu
        key: 083aa0a65aeb292f18afe1f310c17b8d

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
